NCIDCCPS-2153: Creates twig template for webforms.
CBIIT/Cancer-Center-Smoking-Cessation-Toolkit pull request #273
Opened 2020-11-19 14:35 UTC by sasankaj

2020-11-19 16:06 UTC, shashank-naik requested changes

2020-11-19 16:06 UTC, shashank-naik commented on web/themes/custom/digital_toolkit/templates/node/node--webform--full.html.twig
> +{#
Rather than applying this template to all webforms, I am wondering if this template should only apply to the "Radiology Research Opportunities" webform? We could do so by changing the template filename to include the content node id?

2020-11-20 00:09 UTC, sasankaj commented on web/themes/custom/digital_toolkit/templates/node/node--webform--full.html.twig
> +{#
@shashank-naik, I updated the webform template to apply only to this form, by adding the node id to the template name.

2020-11-20 15:37 UTC, shashank-naik approved these changes

2020-11-20 15:37 UTC, merged